owner: K12-Analytics-Engineering
repo: kai-status

sites:
  - name: Kai
    url: https://askkai.org

status-website:
  cname: status.askkai.org
  name: Kai Status


# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
